### PR TITLE
Add server redirects to root dart-lang.github.io

### PR DESCRIPTION
**Pull request by kevmoo**
Will allow us to delete https://github.com/dart-lang/server/

### CODE REVIEW

**Comment by mit-mit** [comment]
Redirects look good, but how will this enable us to delete the repo?

**Comment by mit-mit** [comment]
Oh, I see, this repo has multiple GH Pages instances?

**Comment by kevmoo** [comment]
> Redirects look good, but how will this enable us to delete the repo?

There is fallback logic. If `org.github.io/repo` doesn't exist, 'org/org.github.io/repo` is used.

See the angular bits already here. Those used by be their own repos.

**Comment by kevmoo** [comment]
> Oh, I see, this repo has multiple GH Pages instances?

Something like that. There's a fallback mechanism.

**Review by mit-mit — APPROVED** [review]

**Pull request merged**
